<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Inicio de sesion</title>
	<link href="<?php echo $_layoutParams["route_css"]?>/bootstrap.min.css" rel="stylesheet">
	<link href="<?php echo $_layoutParams["route_css"]?>/bootstrap-material-design.min.css" rel="stylesheet">
	<link href="<?php echo $_layoutParams["route_css"]?>/ripples.min.css" rel="stylesheet">
	<link href="<?php echo $_layoutParams["route_css"]?>/nouislider.min.css" rel="stylesheet">
</head>
<body>

