<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<title>Money Tracking</title>
		<!-- Bootstrap -->
		<link href="<?php echo $_layoutParams["route_css"]?>/bootstrap.min.css" rel="stylesheet">
		<link href="<?php echo $_layoutParams["route_css"]?>/bootstrap-material-design.min.css" rel="stylesheet">
		<link href="<?php echo $_layoutParams["route_css"]?>/ripples.min.css" rel="stylesheet">
		<link href="<?php echo $_layoutParams["route_css"]?>/nouislider.min.css" rel="stylesheet">
		<link href="<?php echo $_layoutParams["route_css"]?>/style.css" rel="stylesheet">
	</head>
	<body>

	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="<?php echo APP_URL; ?>">Money Tracking</a>
			</div>
			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
				<?php if ($_SESSION["type_name"] == "administrador") { ?>
					<li><a href="<?php echo APP_URL."/users/"; ?>">Users</a></li>
					<li><a href="<?php echo APP_URL."/types/"; ?>">Types of users</a></li>
				<?php } ?>
					<li><a href="<?php echo APP_URL."/accounts/"; ?>">Accounts</a></li>
					<li><a href="<?php echo APP_URL."/transactions/"; ?>">Transactions</a></li>
					<li><a href="<?php echo APP_URL."/categories/"; ?>">Categories</a></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Username: <strong><?php echo $_SESSION["username"]; ?></strong> <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<!--<li><a href="#">Account</a></li>-->
							<!--<li role="separator" class="divider"></li>-->
							<li><a href="<?php echo APP_URL."/users/logout"; ?>">Logout</a></li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</nav>